"""Site infrastructure: perimeter fence, access roads and inverter stations.

The core generator deliberately ships just panels and terrain. This module
adds the rest of what a real PV site carries, for establishing shots and
the "wow factor" pass, without touching any of the base panel/terrain
assets.

Two constraints shaped all of this:

* **Seed stability.** Infrastructure draws from its own RNG stream, so
  turning it on or off can't shift a single table. A given seed produces
  the same farm either way, which keeps worlds reproducible and lets both
  be rendered as a matched pair.

* **Triangle budget.** The 1000-module world already holds real time by
  merging geometry instead of instancing it, and the infrastructure has to
  follow the same rule. A 420 m perimeter with posts every 3 m is ~140
  posts; as individual models that's 140 extra entities for the physics
  broadphase and the render queue to walk every frame. Merged into a
  single mesh it's one draw call, so that's what happens below. For the
  same reason, the chain-link fabric is an alpha-textured quad per side
  rather than modelled wire.
"""

import math
import os

import numpy as np
from PIL import Image

from . import pv_textures

FENCE_HEIGHT = 2.10      # m, typical security fence including barb arm
POST_SPACING = 3.00      # m between line posts
POST_SIDE = 0.06         # m, square cross-section
ROAD_WIDTH = 4.00        # m, wide enough for a service vehicle
ROAD_Z = 0.02            # m, raised off the ground plane to avoid z-fighting

# Inverter/transformer skid. Real central inverters for a farm this size
# are roughly container-sized; these are sized like a small skid-mounted
# unit.
INV_SIZE = (2.60, 1.60, 2.10)


# --- textures -----------------------------------------------------------------

def _chainlink_rgba(rng, px=512, pitch=42, wire=4):
    """Tiled chain-link fabric as RGBA, with alpha cut to the wire.

    The diamond lattice is two families of diagonal lines, so it comes
    from the two diagonal coordinates (x+y) and (x-y) taken modulo the
    mesh pitch. Working in the diagonal basis instead of drawing wires one
    at a time is what keeps this exactly tileable.
    """
    yy, xx = np.mgrid[0:px, 0:px]
    d1 = (xx + yy) % pitch
    d2 = (xx - yy) % pitch
    on = ((np.minimum(d1, pitch - d1) < wire) |
          (np.minimum(d2, pitch - d2) < wire))

    # Galvanised steel, with enough tonal noise that a long fence run
    # doesn't read as a flat grey screen at a distance.
    grime = pv_textures.fbm_tileable((px, px), rng, octaves=4, k0=6)
    base = 0.62 + 0.16 * grime
    img = np.zeros((px, px, 4), np.float32)
    img[..., 0] = base * 0.98
    img[..., 1] = base * 1.00
    img[..., 2] = base * 1.03
    img[..., 3] = on.astype(np.float32)
    return img


def _gravel(rng, px=1024):
    """Compacted-gravel access road."""
    coarse = pv_textures.fbm_tileable((px, px), rng, octaves=5, k0=8)
    grit = pv_textures.fbm_tileable((px, px), rng, octaves=3, k0=48)
    img = np.zeros((px, px, 3), np.float32)
    v = 0.34 + 0.22 * coarse + 0.14 * grit
    img[..., 0] = v * 1.04
    img[..., 1] = v * 1.00
    img[..., 2] = v * 0.92
    return np.clip(img, 0.0, 1.0)


def _housing(rng, px=512):
    """Painted sheet-steel housing with faint vertical panel seams."""
    n = pv_textures.fbm_tileable((px, px), rng, octaves=4, k0=10)
    img = np.zeros((px, px, 3), np.float32)
    v = 0.68 + 0.08 * n
    seam = (np.arange(px) % 96 < 2).astype(np.float32)
    v = v - 0.16 * seam[None, :]
    img[..., 0] = v * 0.98
    img[..., 1] = v * 0.99
    img[..., 2] = v * 0.94
    return np.clip(img, 0.0, 1.0)


def build_textures(rng, outdir, asset_pkg):
    tex = os.path.join(outdir, asset_pkg, "materials", "textures")
    os.makedirs(tex, exist_ok=True)

    Image.fromarray(pv_textures.to_u8(_chainlink_rgba(rng)), "RGBA").save(
        os.path.join(tex, "fence_fabric.png"), optimize=True)
    Image.fromarray(pv_textures.to_u8(_gravel(rng)), "RGB").save(
        os.path.join(tex, "road_albedo.png"), optimize=True)
    Image.fromarray(pv_textures.to_u8(_housing(rng)), "RGB").save(
        os.path.join(tex, "inverter_albedo.png"), optimize=True)

    rough = np.clip(0.86 + 0.10 * pv_textures.fbm_tileable(
        (512, 512), rng, octaves=3, k0=12), 0, 1)
    Image.fromarray(pv_textures.to_u8(rough), "L").save(
        os.path.join(tex, "site_roughness.png"), optimize=True)


# --- geometry ------------------------------------------------------------

def _quad(verts, uvs, faces, p0, p1, p2, p3, uv):
    base = len(verts) + 1
    verts += [p0, p1, p2, p3]
    uvs += list(uv)
    faces.append((base, base + 1, base + 2, base + 3))


def _write_obj(path, verts, uvs, faces, normal=(0.0, 0.0, 1.0)):
    with open(path, "w") as f:
        f.write("# generated by solar_farm_gz.site\n")
        for x, y, z in verts:
            f.write(f"v {x:.4f} {y:.4f} {z:.4f}\n")
        for u, v in uvs:
            f.write(f"vt {u:.5f} {v:.5f}\n")
        f.write(f"vn {normal[0]:.4f} {normal[1]:.4f} {normal[2]:.4f}\n")
        for quad in faces:
            f.write("f " + " ".join(f"{i}/{i}/1" for i in quad) + "\n")
    return len(faces)


def write_fence_obj(path, x0, y0, x1, y1):
    """Chain-link fabric as four tiled quads, one per side.

    UVs tile along the run at one mesh repeat per 1.4 m, so the diamond
    size stays physically consistent no matter the side's length.

    Each side carries its own outward normal. It's not a detail that can
    be skipped: the fabric is vertical, so a shared upward-facing normal
    lights every panel as if it were ground, and the fence renders black
    or vanishes entirely. `double_sided` on the material controls culling,
    not shading, and doesn't make up for it.
    """
    verts, uvs, faces, normals = [], [], [], []
    corners = [((x0, y0), (x1, y0)), ((x1, y0), (x1, y1)),
               ((x1, y1), (x0, y1)), ((x0, y1), (x0, y0))]
    for (ax, ay), (bx, by) in corners:
        run = math.hypot(bx - ax, by - ay)
        u = run / 1.4
        # outward normal: the run direction rotated -90 degrees in plan
        nx, ny = (by - ay) / run, -(bx - ax) / run
        normals.append((nx, ny, 0.0))
        base = len(verts) + 1
        verts += [(ax, ay, 0.0), (bx, by, 0.0),
                  (bx, by, FENCE_HEIGHT), (ax, ay, FENCE_HEIGHT)]
        uvs += [(0.0, 0.0), (u, 0.0), (u, 1.0), (0.0, 1.0)]
        faces.append(((base, base + 1, base + 2, base + 3), len(normals)))

    with open(path, "w") as f:
        f.write("# generated by solar_farm_gz.site\n")
        for x, y, z in verts:
            f.write(f"v {x:.4f} {y:.4f} {z:.4f}\n")
        for u, v in uvs:
            f.write(f"vt {u:.5f} {v:.5f}\n")
        for nx, ny, nz in normals:
            f.write(f"vn {nx:.4f} {ny:.4f} {nz:.4f}\n")
        for quad, ni in faces:
            f.write("f " + " ".join(f"{i}/{i}/{ni}" for i in quad) + "\n")
    return len(faces)


def write_posts_obj(path, x0, y0, x1, y1):
    """Line posts merged into a single mesh."""
    from . import pv_mesh
    verts, faces = [], []
    h = FENCE_HEIGHT + 0.08
    s = POST_SIDE

    def run(ax, ay, bx, by):
        length = math.hypot(bx - ax, by - ay)
        n = max(2, int(round(length / POST_SPACING)) + 1)
        for i in range(n):
            t = i / (n - 1)
            pv_mesh._box(verts, faces,
                         ax + (bx - ax) * t, ay + (by - ay) * t, h / 2.0,
                         s, s, h)

    run(x0, y0, x1, y0)
    run(x1, y0, x1, y1)
    run(x1, y1, x0, y1)
    run(x0, y1, x0, y0)

    # Top rail. Chain-link fabric is mostly gaps, so at inspection flight
    # altitude its alpha texture fades to nothing under mipmapping and the
    # perimeter reads as a line of disconnected posts. A real security
    # fence carries a rail along the top, and that continuous horizontal
    # line is what actually makes a fence legible from the air -- so it
    # earns its four boxes.
    r = 0.05
    rz = FENCE_HEIGHT
    pv_mesh._box(verts, faces, (x0 + x1) / 2, y0, rz, x1 - x0, r, r)
    pv_mesh._box(verts, faces, (x0 + x1) / 2, y1, rz, x1 - x0, r, r)
    pv_mesh._box(verts, faces, x0, (y0 + y1) / 2, rz, r, y1 - y0, r)
    pv_mesh._box(verts, faces, x1, (y0 + y1) / 2, rz, r, y1 - y0, r)

    with open(path, "w") as f:
        f.write("# generated by solar_farm_gz.site\n")
        for x, y, z in verts:
            f.write(f"v {x:.4f} {y:.4f} {z:.4f}\n")
        f.write("vt 0.0 0.0\n")
        for nx, ny, nz in pv_mesh._BOX_NORMALS:
            f.write(f"vn {nx} {ny} {nz}\n")
        for quad, ni in faces:
            f.write("f " + " ".join(f"{i}/1/{ni}" for i in quad) + "\n")
    return len(faces)


def road_rect(x0, y0, x1, y1):
    """Centreline of the ring road, set back from the fence.

    The road is drawn around this centreline, so the setback has to clear
    half the road width plus a margin -- otherwise the carriageway rides
    up onto the fence line and gravel renders on both sides of it.
    """
    d = ROAD_WIDTH / 2.0 + 1.0
    return x0 + d, y0 + d, x1 - d, y1 - d


def write_road_obj(path, x0, y0, x1, y1):
    """Perimeter ring road, placed just inside the fence line.

    Four rectangles instead of a real mitred ring: the corners overlap,
    which is invisible over a flat gravel texture and avoids mitre maths.
    """
    x0, y0, x1, y1 = road_rect(x0, y0, x1, y1)
    verts, uvs, faces = [], [], []
    w = ROAD_WIDTH

    def strip(ax, ay, bx, by, horizontal):
        """One carriageway segment.

        Both branches must wind counter-clockwise seen from above, or the
        quad faces the ground and gets backface-culled -- it vanishes
        while its neighbours on the other two sides render normally,
        which looks like a placement bug rather than a winding one.
        """
        if horizontal:
            p = [(ax, ay - w / 2), (bx, ay - w / 2),
                 (bx, ay + w / 2), (ax, ay + w / 2)]
            tile = abs(bx - ax) / 6.0
            uv = [(0.0, 0.0), (tile, 0.0), (tile, 1.0), (0.0, 1.0)]
        else:
            p = [(ax - w / 2, ay), (ax + w / 2, ay),
                 (ax + w / 2, by), (ax - w / 2, by)]
            tile = abs(by - ay) / 6.0
            uv = [(0.0, 0.0), (1.0, 0.0), (1.0, tile), (0.0, tile)]
        _quad(verts, uvs, faces,
              (p[0][0], p[0][1], ROAD_Z), (p[1][0], p[1][1], ROAD_Z),
              (p[2][0], p[2][1], ROAD_Z), (p[3][0], p[3][1], ROAD_Z),
              uv)

    strip(x0, y0, x1, y0, True)
    strip(x0, y1, x1, y1, True)
    strip(x0, y0, x0, y1, False)
    strip(x1, y0, x1, y1, False)
    return _write_obj(path, verts, uvs, faces)


# --- world fragment -----------------------------------------------------

def extent(assignments, span, module_l, margin):
    """Fence rectangle around the array, with an O&M setback."""
    xs = [a[0] for a in assignments]
    ys = [a[1] for a in assignments]
    return (min(xs) - module_l / 2.0 - margin,
            min(ys) - span / 2.0 - margin,
            max(xs) + module_l / 2.0 + margin,
            max(ys) + span / 2.0 + margin)


def inverter_positions(x0, y0, x1, y1, n):
    """Evenly spaced along the inner edge of the west road.

    Takes the fence rectangle and derives the road from it, so the caller
    only has to deal with a single coordinate system.
    """
    rx0, ry0, _, ry1 = road_rect(x0, y0, x1, y1)
    out = []
    for i in range(n):
        t = (i + 0.5) / n
        out.append((rx0 + ROAD_WIDTH / 2.0 + INV_SIZE[0] * 0.7,
                    ry0 + (ry1 - ry0) * t,
                    0.0))
    return out


def sdf(asset_uri, x0, y0, x1, y1, n_inverters, shadows):
    """SDF fragment for all site infrastructure. Static, so no physics cost."""
    cast = 'true' if shadows else 'false'
    rough = asset_uri("materials/textures/site_roughness.png")

    def pbr(albedo, metal=0.0, extra=""):
        return f"""
          <material>
            <ambient>0.28 0.28 0.28 1</ambient>
            <diffuse>1 1 1 1</diffuse>
            <specular>0.3 0.3 0.3 1</specular>{extra}
            <pbr><metal>
              <albedo_map>{asset_uri(albedo)}</albedo_map>
              <roughness_map>{rough}</roughness_map>
              <metalness>{metal}</metalness>
            </metal></pbr>
          </material>"""

    inv = ""
    for i, (ix, iy, _) in enumerate(inverter_positions(x0, y0, x1, y1,
                                                       n_inverters)):
        sx, sy, sz = INV_SIZE
        inv += f"""
    <model name="inverter_{i:02d}">
      <static>true</static>
      <pose>{ix:.3f} {iy:.3f} {sz/2:.3f} 0 0 0</pose>
      <link name="link">
        <collision name="c">
          <geometry><box><size>{sx} {sy} {sz}</size></box></geometry>
        </collision>
        <visual name="v">
          <cast_shadows>{cast}</cast_shadows>
          <geometry><box><size>{sx} {sy} {sz}</size></box></geometry>{pbr(
              "materials/textures/inverter_albedo.png", metal=0.6)}
        </visual>
      </link>
    </model>"""

    return f"""
    <model name="site_road">
      <static>true</static>
      <link name="link">
        <visual name="v">
          <cast_shadows>false</cast_shadows>
          <geometry><mesh><uri>{asset_uri("meshes/road.obj")}</uri></mesh></geometry>{pbr(
              "materials/textures/road_albedo.png")}
        </visual>
      </link>
    </model>

    <model name="site_fence_posts">
      <static>true</static>
      <link name="link">
        <visual name="v">
          <cast_shadows>{cast}</cast_shadows>
          <geometry><mesh><uri>{asset_uri("meshes/fence_posts.obj")}</uri></mesh></geometry>
          <material>
            <ambient>0.22 0.23 0.24 1</ambient>
            <diffuse>0.55 0.57 0.60 1</diffuse>
            <specular>0.4 0.4 0.4 1</specular>
            <pbr><metal><metalness>0.8</metalness>
              <roughness>0.45</roughness></metal></pbr>
          </material>
        </visual>
      </link>
    </model>

    <!--
      The fabric is alpha-cut rather than modelled as wire. double_sided
      is mandatory: a single-sided quad is invisible from outside the
      perimeter, which looks like a fence that vanishes as the drone
      flies past it.
    -->
    <model name="site_fence_fabric">
      <static>true</static>
      <link name="link">
        <visual name="v">
          <cast_shadows>false</cast_shadows>
          <transparency>0.0</transparency>
          <geometry><mesh><uri>{asset_uri("meshes/fence_fabric.obj")}</uri></mesh></geometry>
          <material>
            <double_sided>true</double_sided>
            <ambient>0.35 0.36 0.38 1</ambient>
            <diffuse>1 1 1 1</diffuse>
            <specular>0.25 0.25 0.25 1</specular>
            <pbr><metal>
              <albedo_map>{asset_uri("materials/textures/fence_fabric.png")}</albedo_map>
              <metalness>0.7</metalness>
              <roughness>0.5</roughness>
            </metal></pbr>
          </material>
        </visual>
      </link>
    </model>{inv}"""
